openapi: 3.0.0
info:
  version: 1.0.0
  title: Kids Keeper API Docs
  description: Kids Keeper API 문서
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - description: dev servers
    url: 'http://localhost:3000/api/'
paths:
  /regions:
    get:
      tags:
        - region
      summary: get all regions
      description: null
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    region_id:
                      type: integer
                    region_name:
                      type: string
  '/regions/{id}':
    get:
      tags:
        - region
      summary: get region by id
      description: null
      parameters:
        - name: id
          in: path
          required: true
          description: 구 ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  region_id:
                    type: integer
                  region_name:
                    type: string
  '/regions/{name}':
    get:
      tags:
        - region
      summary: get region by name
      description: null
      parameters:
        - name: name
          in: path
          required: true
          description: 구 이름
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  region_id:
                    type: integer
                  region_name:
                    type: string
  /centers:
    get:
      tags:
        - children care center
      summary: get all centers
      description: null
      parameters:
        - name: region
          in: query
          required: false
          description: 구 이름
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    center_id:
                      type: integer
                    name:
                      type: string
                    lat:
                      type: number
                    lng:
                      type: number
                    region_id:
                      type: integer
                    region_name:
                      type: string
  '/centers/{id}':
    get:
      tags:
        - children care center
      summary: get centers by center id
      description: null
      parameters:
        - name: id
          in: path
          required: true
          description: 어린이집 ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  center_id:
                    type: integer
                  name:
                    type: string
                  lat:
                    type: number
                  lng:
                    type: number
                  region_id:
                    type: integer
                  region_name:
                    type: string
  '/centers/{name}':
    get:
      tags:
        - children care center
      summary: get centers by name
      description: null
      parameters:
        - name: name
          in: path
          required: true
          description: 어린이집 이름
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  center_id:
                    type: integer
                  name:
                    type: string
                  lat:
                    type: number
                  lng:
                    type: number
                  region_id:
                    type: integer
                  region_name:
                    type: string
tags:
  - name: region
  - name: children care center
